#!/bin/ash
if [ ! -f /config/nginx/nginx.conf ]; then
    cp /defaults/nginx/nginx.conf /config/nginx/nginx.conf
fi

if [ ! -f /config/nginx/sites/default.conf ]; then
    cp /defaults/nginx/sites/default.conf /config/nginx/sites/default.conf
fi

if [ ! -f /config/www/default.html ]; then
    cp /defaults/www/default.html /config/www/default.html
fi

if [ ! -f /config/nginx/ssl-default.conf ]; then
    cp /defaults/nginx/ssl-default.conf /config/nginx/ssl-default.conf
fi