name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      dockerfile-path:
        required: true
        type: string
      dockerhub-path:
        required: true
        type: string

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images:
          ${{ inputs.dockerhub-path }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile-path }}
        push: true
        tags: latest
        labels: ${{ steps.meta.outputs.labels }}
