name: Build Nextcloud Image

on:
  workflow_dispatch:
  push:
    paths:
      - './Nextcloud/**'
      
jobs:
  call-workflow-passing-data:
    uses: .github/workflows/docker-image.yml@main
    with:
      dockerfile-path: Nextcloud/Dockerfile
      dockerhub-path: prowler1000/nextcloud-with-extras
    secrets: inherit
